# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04710f865b9ac6d3ff03160ad0a417fc63b0b3baa761d2943696d1968de6fbba3ffcd6dda76172b2109d6d5eb3c2fcaec771713c65f41c406fe869890c92b6b5

test:
  secret_key_base: 975eef4151a0705b552f88b80ccf2d38725c76ba5afc94b32a6d0e6c6ec82618dd8f624e6f6d3202d1e751f8b90964663d5b5e63fd3e18fbdd7e9dad57746156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
